---
layout: cv
title: Andrew Flinders
---
# Resume
Accounting Student at BYUI 

<div id="webaddress">
<a href="atflind@gmail.com">atflind@gmail.com</a>
| <a href="https://www.linkedin.com/in/andrew-flinders/">My Linked-In Page</a>
</div>


## Currently

Studying Accounting at Brigham Young Universtiy Idaho

### Interests

Games of all types, country dancing, gospel studies, and history

## Education

`2016 - 2020`

### __Etiwanda High School__

`2020 - 2022`

### __George Mason University__

- Student

`2025 - current`

### __Brigham Young University Idaho__

- Studying Accounting


## Awards

`2016`

  -  Eagle Scout


## Experience

`January 2023 - December 2024`
The Church of Jesus Christ of Latter-day Saints - 
Full-Time Volunteer Representative;              
Salt Lake City, UT 
  -  Learned to speak Spanish professionally within 2 years of starting 
  -  Managed 84 hour work weeks and traveled over 30 miles a day

`August 2022 - December 2022`  
Harmon's Grocery Stores - E-shop associate;                                                    
Salt Lake City, UT              
  -   Completed 10 plus online orders for customers by a specific date and time while working in teams each day
  -   Communicated with 20 plus customers a day in a way to guarantee happiness; providedcustomer with choices the customer did not know about

`August 2021 - May 2022`  
Giant Foods - Cashier and Customer Service Representative;                                      
Fairfax, VA
  -  Operated a cash register and efficiently communicated with 20 plus customers to satisfycustomers needs
  -  Trained more than 2 employees on how to operate a cash register and how to treat customers,how to start conversations, and how to de-escalate angry or stressed out customers.
  -  Operated Western Union helping 5 plus people every day to transfer money to other countries

`August 2018 - August 2020`  
Flinders Insurance Agency Inc/ DBA DePalma Insurance - Clerk;                                  
Burbank, CA
  -  Performed clerical work allowing paperwork to be uploaded digitally for easier access


## Skills
  -  Leadership oriented and service driven
  -  Technical: Microsoft Office Suite and other software
  -  Forklift Certified
  -  Familiar with Python, Machine Learning, and MySql


<!-- ### Footer

Last updated: May 2013 -->